export const mockAlerts = [
  {
    id: "1",
    type: "Flood",
    location: "Downtown, San Francisco",
    coordinates: { lat: 37.7749, lng: -122.4194 },
    severity: "high",
    timestamp: "2025-04-15T08:15:00Z",
    description: "Flash flooding reported in downtown area. Multiple streets underwater. Avoid downtown if possible.",
    distance: 2.3,
  },
  {
    id: "2",
    type: "Earthquake",
    location: "Oakland, CA",
    coordinates: { lat: 37.8044, lng: -122.2711 },
    severity: "medium",
    timestamp: "2025-04-15T07:58:00Z",
    description: "Magnitude 4.2 earthquake detected. Minor damage reported to some structures.",
    distance: 8.7,
  },
  {
    id: "3",
    type: "Wildfire",
    location: "Marin County, CA",
    coordinates: { lat: 38.0834, lng: -122.7633 },
    severity: "high",
    timestamp: "2025-04-15T06:30:00Z",
    description: "Rapidly spreading wildfire. Evacuation orders in effect for northern Marin County.",
    distance: 24.5,
  },
  {
    id: "4",
    type: "Hurricane",
    location: "Coastal Areas, CA",
    coordinates: { lat: 37.5834, lng: -122.9633 },
    severity: "medium",
    timestamp: "2025-04-15T05:45:00Z",
    description: "Hurricane warning issued for coastal areas. High winds and storm surge expected.",
    distance: 35.2,
  },
  {
    id: "5",
    type: "Tornado",
    location: "South San Jose, CA",
    coordinates: { lat: 37.2751, lng: -121.8261 },
    severity: "high",
    timestamp: "2025-04-15T08:05:00Z",
    description: "Tornado warning in effect. Take shelter immediately in a basement or interior room.",
    distance: 42.8,
  },
  {
    id: "6",
    type: "Landslide",
    location: "Berkeley Hills, CA",
    coordinates: { lat: 37.8789, lng: -122.2356 },
    severity: "low",
    timestamp: "2025-04-15T07:20:00Z",
    description: "Minor landslide reported on eastern slopes. Some roads may be affected.",
    distance: 12.3,
  },
  {
    id: "7",
    type: "Flood",
    location: "Palo Alto, CA",
    coordinates: { lat: 37.4419, lng: -122.143 },
    severity: "medium",
    timestamp: "2025-04-15T08:10:00Z",
    description: "Rising water levels in low-lying areas. Some street flooding reported.",
    distance: 30.1,
  },
]
